# Generated by Django 3.2.8 on 2021-11-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Название региона')),
                ('capital', models.FloatField(verbose_name='Капитал')),
                ('area', models.FloatField(verbose_name='Площадь')),
                ('population', models.FloatField(verbose_name='Население')),
                ('fertility', models.TextField(verbose_name='Плодородие')),
                ('minerals', models.TextField(verbose_name='Полезные ископаемые')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
                'ordering': ('name',),
            },
        ),
    ]
