# Generated by Django 3.2.8 on 2021-11-12 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Название города')),
                ('wealth', models.TextField(verbose_name='Богатство')),
                ('area', models.FloatField(verbose_name='Площадь')),
                ('population', models.FloatField(verbose_name='Население')),
                ('pleasure', models.TextField(verbose_name='Удовлетворение')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='countries.countries', verbose_name='Страна')),
            ],
        ),
    ]
