# Generated by Django 3.2.8 on 2021-11-15 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Город проживания'),
        ),
        migrations.AlterField(
            model_name='user',
            name='money',
            field=models.FloatField(blank=True, null=True, verbose_name='Денежные средства'),
        ),
    ]
